[workspace]
resolver = "3"
members = ["crates/aotc", "crates/core"]

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/seliumlabs/wasmtiny"
license = "MPL-2.0"

[workspace.dependencies]
anyhow = { version = "1.0", default-features = false }
clap = { version = "4.6", default-features = false }
cranelift-codegen = { version = "0.111", default-features = false }
cranelift-entity = { version = "0.111", default-features = false }
cranelift-frontend = { version = "0.111", default-features = false }
cranelift-wasm = { version = "0.111", default-features = false }
libc = { version = "0.2", default-features = false }
parking_lot = { version = "0.12", default-features = false }
sha2 = { version = "0.10", default-features = false }
target-lexicon = { version = "0.12", default-features = false }
thiserror = { version = "2.0", default-features = false }
walkdir = { version = "2.5", default-features = false }
wasmparser = { version = "0.215", default-features = false }
wasmtiny = { path = "crates/core", default-features = false }
wasmtiny-aotc = { path = "crates/aotc", default-features = false }
wast = { version = "259.0", default-features = false }
wat = { version = "1.259", default-features = false }
