//! Cross-boundary trampolines and stubs, generated by Cranelift so that all
//! ABI knowledge stays inside the compiler.
//!
//! - **Entry trampoline** (host → wasm): a fixed array-call signature.
//! - **Host-call stub** (wasm → host): bridges an imported function's native
//!   ABI to a fixed-signature runtime dispatcher.

use cranelift_codegen::ir::immediates::Offset32;
use cranelift_codegen::ir::{
    self, AbiParam, GlobalValueData, InstBuilder, MemFlags, Signature, StackSlotData,
    StackSlotKind, UserFuncName, types,
};
use cranelift_codegen::isa::CallConv;
use cranelift_frontend::{FunctionBuilder, FunctionBuilderContext};
use cranelift_wasm::{WasmFuncType, WasmValType};

use crate::environment::{LibCallOffsets, VmCtxOffsets};

/// The native CLIF type used for each wasm value type.
fn value_clif_type(ty: &WasmValType) -> ir::Type {
    match ty {
        WasmValType::I32 => types::I32,
        WasmValType::I64 => types::I64,
        WasmValType::F32 => types::F32,
        WasmValType::F64 => types::F64,
        WasmValType::V128 => types::I8X16,
        // References are raw u32 handles.
        WasmValType::Ref(_) => types::I32,
    }
}

/// Converts a typed CLIF value into its 64-bit array-call slot.
fn value_to_slot(builder: &mut FunctionBuilder, value: ir::Value) -> ir::Value {
    match builder.func.dfg.value_type(value) {
        types::I32 => builder.ins().uextend(types::I64, value),
        types::I64 => value,
        types::F32 => {
            let bits = builder.ins().bitcast(types::I32, MemFlags::new(), value);
            builder.ins().uextend(types::I64, bits)
        }
        types::F64 => builder.ins().bitcast(types::I64, MemFlags::new(), value),
        other => unreachable!("unsupported bridging value type {other:?}"),
    }
}

/// Converts a 64-bit slot into the given typed CLIF value.
fn slot_to_value(builder: &mut FunctionBuilder, raw: ir::Value, ty: ir::Type) -> ir::Value {
    match ty {
        types::I32 => builder.ins().ireduce(types::I32, raw),
        types::I64 => raw,
        types::F32 => {
            let bits = builder.ins().ireduce(types::I32, raw);
            builder.ins().bitcast(types::F32, MemFlags::new(), bits)
        }
        types::F64 => builder.ins().bitcast(types::F64, MemFlags::new(), raw),
        other => unreachable!("unsupported bridging value type {other:?}"),
    }
}

/// Builds an array-call entry trampoline for a callee with `callee_sig`
/// (already `vmctx`-augmented) and `wasm_type`.
///
/// Signature: `(vmctx: ptr, callee: ptr, args: *const u64, results: *mut u64) -> ()`.
pub fn build_entry_trampoline(
    call_conv: CallConv,
    callee_sig: &Signature,
    wasm_type: &WasmFuncType,
    type_idx: u32,
) -> ir::Function {
    let pointer_type = types::I64;

    let mut sig = Signature::new(call_conv);
    for _ in 0..4 {
        sig.params.push(AbiParam::new(pointer_type));
    }

    let mut func =
        ir::Function::with_name_signature(UserFuncName::user(0, 0x8000_0000 | type_idx), sig);

    let mut ctx = FunctionBuilderContext::new();
    let mut builder = FunctionBuilder::new(&mut func, &mut ctx);
    let entry = builder.create_block();
    builder.append_block_params_for_function_params(entry);
    builder.switch_to_block(entry);
    builder.seal_block(entry);
    builder.ensure_inserted_block();

    let params = builder.block_params(entry).to_vec();
    let vmctx = params[0];
    let callee = params[1];
    let args_ptr = params[2];
    let results_ptr = params[3];

    let mem_flags = MemFlags::trusted();
    let slot_size = 8i64;

    let mut call_args: Vec<ir::Value> = Vec::with_capacity(wasm_type.params().len() + 1);
    call_args.push(vmctx);
    for (index, param) in wasm_type.params().iter().enumerate() {
        let addr = builder.ins().iadd_imm(args_ptr, index as i64 * slot_size);
        let raw = builder.ins().load(pointer_type, mem_flags, addr, 0);
        call_args.push(slot_to_value(&mut builder, raw, value_clif_type(param)));
    }

    let callee_sig_ref = builder.func.import_signature(callee_sig.clone());
    let call = builder
        .ins()
        .call_indirect(callee_sig_ref, callee, &call_args);
    let results = builder.inst_results(call).to_vec();

    for (index, result) in results.iter().enumerate() {
        let wide = value_to_slot(&mut builder, *result);
        let addr = builder
            .ins()
            .iadd_imm(results_ptr, index as i64 * slot_size);
        builder.ins().store(mem_flags, wide, addr, 0);
    }

    builder.ins().return_(&[]);
    builder.finalize();

    func
}

/// Builds a host-call stub for an imported function with `callee_sig` (already
/// `vmctx`-augmented), `wasm_type`, and a baked-in `import_ordinal`.
///
/// The stub marshals its native arguments into a scratch array, calls the
/// runtime `host_call` libcall, traps on a non-zero result status, and returns
/// the results.
pub fn build_host_call_stub(
    call_conv: CallConv,
    callee_sig: &Signature,
    wasm_type: &WasmFuncType,
    import_ordinal: u32,
) -> ir::Function {
    let pointer_type = types::I64;
    let name = UserFuncName::user(0, 0xC000_0000 | import_ordinal);

    let mut host_sig = Signature::new(call_conv);
    for _ in 0..4 {
        host_sig.params.push(AbiParam::new(pointer_type));
    }
    host_sig.returns.push(AbiParam::new(pointer_type));

    let mut func = ir::Function::with_name_signature(name, callee_sig.clone());
    let host_sig_ref = func.import_signature(host_sig);

    let mut ctx = FunctionBuilderContext::new();
    let mut builder = FunctionBuilder::new(&mut func, &mut ctx);
    let entry = builder.create_block();
    builder.append_block_params_for_function_params(entry);
    let block_params = builder.block_params(entry).to_vec();
    builder.switch_to_block(entry);
    builder.seal_block(entry);
    builder.ensure_inserted_block();

    let vmctx = block_params[0];
    let wasm_params = &block_params[1..];
    let mem_flags = MemFlags::trusted();

    let param_count = wasm_type.params().len();
    let result_count = wasm_type.returns().len();

    let args_slot = builder.create_sized_stack_slot(StackSlotData::new(
        StackSlotKind::ExplicitSlot,
        (param_count * 8) as u32,
        3,
    ));
    let results_slot = builder.create_sized_stack_slot(StackSlotData::new(
        StackSlotKind::ExplicitSlot,
        (result_count * 8) as u32,
        3,
    ));

    for (index, value) in wasm_params.iter().enumerate() {
        let wide = value_to_slot(&mut builder, *value);
        let addr = builder
            .ins()
            .stack_addr(pointer_type, args_slot, (index * 8) as i32);
        builder.ins().store(mem_flags, wide, addr, 0);
    }

    let vmctx_gv = builder.func.create_global_value(GlobalValueData::VMContext);
    let libcalls_gv = builder.func.create_global_value(GlobalValueData::Load {
        base: vmctx_gv,
        offset: Offset32::new(VmCtxOffsets::LIBCALLS),
        global_type: pointer_type,
        flags: MemFlags::trusted().with_readonly(),
    });
    let libcalls_base = builder.ins().global_value(pointer_type, libcalls_gv);
    let host_call_fn = builder.ins().load(
        pointer_type,
        MemFlags::trusted(),
        libcalls_base,
        LibCallOffsets::HOST_CALL,
    );

    let args_addr = builder.ins().stack_addr(pointer_type, args_slot, 0);
    let results_addr = builder.ins().stack_addr(pointer_type, results_slot, 0);
    let ordinal = builder
        .ins()
        .iconst(pointer_type, i64::from(import_ordinal));

    let call = builder.ins().call_indirect(
        host_sig_ref,
        host_call_fn,
        &[vmctx, ordinal, args_addr, results_addr],
    );
    let status = builder.inst_results(call)[0];
    builder.ins().trapnz(status, ir::TrapCode::User(0));

    let mut retvals = Vec::with_capacity(result_count);
    for (index, result) in wasm_type.returns().iter().enumerate() {
        let addr = builder
            .ins()
            .stack_addr(pointer_type, results_slot, (index * 8) as i32);
        let raw = builder.ins().load(pointer_type, mem_flags, addr, 0);
        retvals.push(slot_to_value(&mut builder, raw, value_clif_type(result)));
    }

    builder.ins().return_(&retvals);
    builder.finalize();

    func
}
